name: CI & github packaging

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build and Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          mvn clean deploy
          -Papi-tests-infrastructure
          -Papi-tests
          -Dpostgres.user=${{secrets.POSTGRES_USER}}
          -Dpostgres.password=${{secrets.POSTGRES_PASSWORD}}
          -Dhome.application.admin.username=${{secrets.HOME_APPLICATION_ADMIN_USERNAME}}
          -Dhome.application.admin.password=${{secrets.HOME_APPLICATION_ADMIN_PASSWORD}}
